version: 1.0.{build}

environment:
  matrix:
    - perl: "5.14.4.1"
    - perl: "5.16.3.20170202"
    - perl: "5.18.4.1"
    - perl: "5.20.3.3"
    - perl: "5.22.3.1"
    - perl: "5.24.1.1"

platform:
  - x86
  - x64

services:
  - mysql

install:
  - if /I %PLATFORM% == x86 (set x86=--forcex86) else (set "x86= ")
  - cinst StrawberryPerl --version %perl% %x86% --allow-empty-checksums
  - path C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - mkdir %APPVEYOR_BUILD_FOLDER%\tmp
  - set TMPDIR=%APPVEYOR_BUILD_FOLDER%\tmp
  - perl -V
  - cpan App::cpanminus
  - cpanm -q --showdeps --with-develop --with-suggests . | findstr /v "^perl\>" | cpanm -n
  - cpanm -q -n Devel::CheckLib

build_script:
  - perl Makefile.PL --mysql_config=c:\strawberry\c\bin\mysql_config.bat --testuser=root --testpassword=Password12!

test_script:
  - dmake test
